name: Daily Profile Update

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Update timestamp in README
        run: |
          FILE="profile/README.md"
          DATE="$(TZ='Asia/Singapore' date +'%Y-%m-%d')"

          # Replace only the line containing the marker
          sed -i "s|Last Updated:.*|Last Updated: <!--LAST_UPDATED--> $DATE|g" $FILE

      - name: Commit and push
        run: |
          git config --global user.name "Jason3002"
          git config --global user.email "fsv96ss65p@privaterelay.appleid.com"

          git add profile/README.md
          git commit -m "chore: update profile timestamp" || exit 0
          git push origin main
