name: Sync Labels

on:
  workflow_call:

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Sync labels from organization config
        uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/StellaXLabs/.github/main/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
